use_frameworks!

pod 'Alamofire', '4.6.0'
pod 'SwiftyJSON', '4.0.0'

target 'TrafficBase_Example' do
  pod 'TrafficBase', :path => '../'

  target 'TrafficBase_Tests' do
    inherit! :search_paths

    
  end
end
